site_name: lesslines
site_description: explore python with less lines of code
site_author: Sparisoma Viridi
docs_dir: docs
site_dir: site
theme:
  name: material
  features:
    - navigation.tabs
    - search.highlight
    - content.tabs
  palette:
    scheme: light
    primary: indigo
    accent: pink

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dudung
      name: GitHub
    - icon: fontawesome/brands/medium
      link: https://medium.com/@6unpnp
      name: Medium
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/6unpnp
      name: X (formerly Twitter)

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Usage: usage.md
  - Notes: notes.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          options:
            show_source: true
