site_name: lesslines
site_description: explore python with less lines of code
site_author: Sparisoma Viridi
docs_dir: docs
site_dir: site
theme:
  name: material
  features:
    - navigation.tabs
    - search.highlight
    - content.tabs
  palette:
    scheme: light
    primary: indigo
    accent: pink
  footer:
    copyright: "© 2025 Sparisoma Viridi"

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Usage: usage.md
  - Notes: notes.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          options:
            show_source: true
