name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main  # or the branch where you make changes
    paths:
      - 'docs/**'  # Only trigger on changes to docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocstrings[python]

      - name: Build documentation
        run: mkdocs build --strict

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MKDOCS_GH_PAGES }}
          publish_dir: ./site
          commit_message: 'Deploy MkDocs site'
          force_orphan: true
